name: Run Integration Tests
on:
  push:
    branches:
      - yigit/use-ci-action-dist-tag

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    name: Run integration tests on FTL
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "set output directory"
        run: echo "::set-output name=output-dir::$(readlink -f .)/outputs"
        id: dirs
      - id: run_tests
        uses: androidX/androidx-ci-action@dist-v0.01
        with:
          target-run-id: 965174273
          gcp-token: ${{ secrets.GCP_SA_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-folder: ${{ steps.dirs.outputs.output-dir }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: ${{ steps.dirs.outputs.output-dir }}
